### ISSUE TITLE
It seems that the socket address needs to be bound

### ISSUE THREAD

**Issue by karuxkaru** [hrichharms/AlbiPy#2]
```
            udpsock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            udpsock.bind(('', 9654))

            data = udpsock.recvfrom(1250)[0]
```
it that right?

**Comment by hrichharms** [comment]
> ```
>             udpsock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
>             udpsock.bind(('', 9654))
> 
>             data = udpsock.recvfrom(1250)[0]
> ```
> 
> it that right?

The socket does not need to be bound, the socket is technically receiving on all ports. If you try to bind the socket to the client's port it throws an error.

**Comment by karuxkaru** [comment]
if i delete it. it will happen 
[winerror 10013] an attempt to access a socket was made in a way that access rights do not allow.

**Comment by karuxkaru** [comment]
What should I do

**Comment by hrichharms** [comment]
> What should I do

That's my bad. I should add to the readme that it requires admin access.
