### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by karuxkaru** [hrichharms/AlbiPy#3]
when i got the administrator/root access. and then i run the program.but it doesnt work.Nothing print.i dont know if it work.

**Comment by hrichharms** [comment]
Did your client actually receive data during that time? I.e. did you refresh market orders, search market orders etc.?

**Comment by karuxkaru** [comment]
of course.i do this.
i think it still a broblem for port. i also add `self.sniffer.bind(('',2322))`. if i delete it.i will happen a new error.
OSError: [WinError 10013] An attempt was made to access the socket in a way that is not allowed by the access permissions.

**Comment by hrichharms** [comment]
Alright I seem to have found the problem. The socket protocol being used doesn't behave the same way on Windows as on Linux. If you have access to a Linux machine I would recommend using that for the time being until I find a workaround for Windows.

**Comment by AIshouldbecry** [comment]
oh.that is the reason why i cant use the program.ty.

**Comment by hrichharms** [comment]
I just pushed a new version of the file with windows support

**Comment by karuxkaru** [comment]
nice bro.i will try now.

**Comment by karuxkaru** [comment]
it can work stable. what is that mean?  `self.sniffer.ioctl(socket.SIO_RCVALL, socket.RCVALL_ON)`

**Comment by hrichharms** [comment]
it sets the socket mode to receive all as set out by the Microsoft documentation found [here](https://docs.microsoft.com/en-us/windows/win32/winsock/sio-rcvall)

**Comment by AIshouldbecry** [comment]
I will test tomorrow.but it seems to not work on windows system.it doesn’t generate csv file.

**Comment by hrichharms** [comment]
Are you running one of the example scripts or are you running AlbiPy through your own code?

**Comment by AIshouldbecry** [comment]
I run example scripts.it seem can not get what I doing.I will talk to you tomorrow in detail.

**Comment by karuxkaru** [comment]
it my false.i wrong.it can work good in windows system.
![image](https://user-images.githubusercontent.com/74653514/101554378-6cf4b000-39ae-11eb-8117-2dad06cd3ad9.png)
