### ISSUE TITLE
script don't show correctly items KNUCKLES_MORGANA

### ISSUE THREAD

**Issue by madvac** [hrichharms/AlbiPy#6]
Hello,
i found that the script don't show correctly 

"KNUCKLES_MORGANA" (.3 .2) (it show only few items from market)
T5_2H_KNUCKLES_MORGANA (not show)

Thanks.

**Comment by hrichharms** [comment]
@madvac any chance you can send raw sniffer logs? I might get a better idea at what is going wrong with that

**Comment by madvac** [comment]
Hello,

well i dont know how to get raw logs (have zero programming experience).  I am now using your "examples".
If you tell me how to get raw logs, i can send it to you.
THX for your time.

**Comment by hrichharms** [comment]
@madvac ok, is this problem only happening on one computer or at one in game market? If these aren't helpful I can chat with you on discord to work out ur issue.

**Comment by madvac** [comment]
hi

is there any chance to write me how to get raw logs ...or is it too 
difficult?

i test it in HO, bridgewatch, carleon (so i think it do it on all 
markers).

i can try it on anotoher PC (tomorow i try it on linux client)

some times if there only 2 items it dont show any output....
if there is 3 items it show sometime 1, sometime only 2.

But maybe its my side problem.

P.S.: diskcord: I cant speak too much english.

Dne 14.04.2022 17:53, Heinrich Harms napsal:

**Comment by madvac** [comment]
Hi,
i have raw packet log.
u can contact me on discord: madvac#5584
i will send u also output from script.
