### ISSUE TITLE
Is it broken after the recent patch?

### ISSUE THREAD

**Issue by OmerFarukOruc** [hrichharms/AlbiPy#9]
As title says.

**Comment by hrichharms** [comment]
checking it out

**Comment by OmerFarukOruc** [comment]
any news?

**Comment by hrichharms** [comment]
@OmerFarukOruc  been unusually busy lately, any idea on specifically
 what broke it?

**Comment by OmerFarukOruc** [comment]
i guess after mists update, it seems i cant use the script.

**Comment by OmerFarukOruc** [comment]
Hello. Any news mate?
